[package]
name = "lens"
version = "0.0.8"
authors = ["Xyzt Toe <584605539@qq.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html


[dependencies]
lens_derive = { path = "lens_derive/"}