[package]
name = "lens-rs_derive"
version = "0.0.5"
authors = ["Xyzt Toe <584605539@qq.com>"]
edition = "2018"
license = "MIT/Apache-2.0"
readme = "readme.md"
categories = [ "rust-patterns" ]
keywords = [ "pattern matching", "tarevsesing", "lens"]
repository = "https://github.com/TOETOE55/lens-rs/lens-rs_derive"
description = "macro to derive lens for data type"

[lib]
proc-macro = true

[dependencies]
syn = "1.0"
quote = "1.0"
proc-macro2 = "1.0"